UploadThing.Example.AspNetCoreMVC/Models/ErrorViewModel.cs
namespace UploadThing.Example.AspNetCoreMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UploadThing.Example.AspNetCoreMVC/Controllers/AjaxFormUploadController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using UploadThing.Core;

namespace UploadThing.Example.AspNetCoreMVC.Controllers
{
    public class AjaxFormUploadController : Controller
    {
        private UploadThingOptions options;

        public AjaxFormUploadController(IOptions<UploadThingOptions> options)
        {
            this.options = options.Value;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                return BadRequest("No file selected.");
            }

            var uploader = new Uploader(options).
                MaxSize(10); // 10 MB

            var fs = file.OpenReadStream();
            var fileType = UtUtils.GetFileTypeFromMimeType(file.ContentType);

            var uploadFile = new FileDetails(
                FileName: file.FileName,
                FileType: fileType,
                CallbackSlug: "it_is_from_dotnet",
                CallbackUrl: "https://5289-103-149-142-229.ngrok-free.app/api/utcallback"
                //CallbackUrl: "https://c6f2-103-149-142-229.ngrok-free.app"
                );

            try
            {
                var utFile = await uploader.UploadAsync(fs, uploadFile);
                return Json(new { url = utFile });
            }
            catch (UploadThingS3Exception s3Exception)
            {
                return BadRequest(Json("Error - " + s3Exception.Message));
            }
            catch (UploadThingException utException)
            {
                return BadRequest(Json("Error - " + utException.Message));
            }
            catch (Exception ex)
            {
                return BadRequest(Json("Error - " + ex.Message));
            }
        }
    }
}

UploadThing.Example.AspNetCoreMVC/Controllers/CallbackController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System.Text;

namespace UploadThing.Example.AspNetCoreMVC.Controllers
{
    [Route("api/utcallback")]
    [ApiController]
    public class CallbackController : Controller
    {
        private readonly IHubContext<AlertHub> hubContext;

        public CallbackController(IHubContext<AlertHub> hubContext)
        {
            this.hubContext = hubContext;
        }

        [HttpPost]
        public async Task<IActionResult> PostAsync(string slug)
        {
            string jsonString;
            using (StreamReader reader = new StreamReader(Request.Body, Encoding.UTF8))
            {
                jsonString = await reader.ReadToEndAsync();
            }
            await hubContext.Clients.All.SendAsync(
                "ReceiveAlert",
                $"Slug: {slug}<br>Content:<br>{jsonString}"
            );
            return Ok();
        }
    }
}

UploadThing.Example.AspNetCoreMVC/Controllers/FormUploadController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using UploadThing.Core;

namespace UploadThing.Example.AspNetCoreMVC.Controllers
{
    public class FormUploadController : Controller
    {
        private UploadThingOptions config;

        public FormUploadController(IOptions<UploadThingOptions> options)
        {
            this.config = options.Value;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Upload(string slug, IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                TempData["ErrorMessage"] = "No File selected";
                return BadRequest("No file selected.");
            }

            var uploader = new Uploader(config).
                MaxSize(10); // 10 MB
            var fs = file.OpenReadStream();
            var fileType = UtUtils.GetFileTypeFromMimeType(file.ContentType);

            var uploadFile = new FileDetails(
                FileName: file.FileName,
                FileType: fileType,
                CallbackSlug: slug,
                CallbackUrl: "https://5289-103-149-142-229.ngrok-free.app/api/utcallback"
                //CallbackUrl: "https://c6f2-103-149-142-229.ngrok-free.app"
                );

            try
            {
                var utFile = await uploader.UploadAsync(fs, uploadFile);
                TempData["SuccessMessage"] = $"File Uploaded successfully.";
                TempData["DownloadUrl"] = utFile;
            }
            catch (UploadThingS3Exception s3Exception)
            {
                string errorMsg = "Error - " + s3Exception.Message;
                TempData["ErrorMessage"] = errorMsg;
            }
            catch (UploadThingException utException)
            {
                string errorMsg = "Error - " + utException.Message;
                TempData["ErrorMessage"] = errorMsg;
            }
            catch (Exception ex)
            {
                string errorMsg = "Error - " + ex.Message;
                TempData["ErrorMessage"] = errorMsg;
            }
            return RedirectToAction("Index");
        }
    }
}

UploadThing.Example.AspNetCoreMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System.Diagnostics;
using UploadThing.Core;
using UploadThing.Example.AspNetCoreMVC.Models;

namespace UploadThing.Example.AspNetCoreMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, IOptions<UploadThingOptions> options) 
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UploadThing.Example.AspNetCoreMVC/Views/AjaxFormUpload/Index.cshtml
@{
    ViewData["Title"] = "Ajax Form Upload - UT";
}

<div class="text-center">
    <h1 class="display-6">AJAX Form Upload</h1>
    <form enctype="multipart/form-data">
        <div class="form-group">
            <input type="file" class="form-control-file" id="file" name="file" accept="image/*" style="display: none;">
            <button type="button" class="btn btn-primary" onclick="selectFile()" style="width: 100px !important; height:40px !important">
                <div class="d-flex flex-row g-4 align-items-center justify-content-center">
                    <span id="spinner" class="spinner-border spinner-border-sm" role="status" aria-hidden="true" style="display: none;"></span>
                    <div id="submit-btn-text" class="ml-1" style="display: block;">Upload</div>
                </div>
            </button>
            <span id="file-name"></span>
        </div>
        <div style="margin-top:15px">
            <div id="result"></div>
            <a id="download-link" href="" target="_blank" style="display: none;">Download file</a>
        </div>
    </form>
</div>

<script>
    function selectFile() {
        let fileInput = document.getElementById('file');
        let tmpFileInput = fileInput.cloneNode(true);
        fileInput.parentNode.replaceChild(tmpFileInput, fileInput);
        fileInput.files.length = 0;
        fileInput.click();
        fileInput.addEventListener('change', (e) => {
            const selectedFile = fileInput.files[0];
            uploadFile(selectedFile);
        });
    }

    async function uploadFile (selectedFile) {
        if (!selectedFile) {
            return;
        }

        const submitBtnText = document.getElementById("submit-btn-text");
        const resultElement = document.getElementById("result");
        const spinnerElement = document.getElementById('spinner');
        const downloadElement = document.getElementById("download-link");

        spinnerElement.style.display = 'block';
        submitBtnText.style.display = 'none';
        resultElement.innerText = '';
        downloadElement.style.display = 'none';

        const formData = new FormData();
        formData.append('file', selectedFile);

        try {
            const response = await fetch("./AjaxFormUpload/Upload", {
                method: 'POST',
                body: formData
            });

            const jsonObj = await response.json();
            console.log(jsonObj);

            if(response.status == 200) {
                resultElement.innerText = 'Your file made it to UploadThing!';

                downloadElement.href = jsonObj.url;
                downloadElement.style.display = 'inline';
            }
            else {
                resultElement.innerText = jsonObj.value;
            }

            spinnerElement.style.display = 'none';
            submitBtnText.style.display = 'block';
      } catch (error) {
            console.error('Error:', error);
      }
    }
</script>

UploadThing.Example.AspNetCoreMVC/Views/FormUpload/Index.cshtml
@{
    ViewData["Title"] = "Form Upload - UT";
}

<div class="text-center">
    <h1 class="display-6">Form Upload</h1>

    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">
            @TempData["SuccessMessage"]
            <a href="@TempData["DownloadUrl"]" target="_blank"> Download here.</a>
        </div>
    }

    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger">
            @TempData["ErrorMessage"]
        </div>
    }

    <form action="./FormUpload/Upload" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <div class="mb-3">
                <label for="file" class="form-label">Select a File:</label>
                <input type="file" class="form-control" name="file" id="file" accept="image/*" />
            </div>
            <div class="mb-3">
                <label for="slug" class="form-label">Enter Slug:</label>
                <input type="text" class="form-control" name="slug" id="slugInput" />
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

UploadThing.Example.AspNetCoreMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">UploadThing</h1>

    <a class="btn btn-secondary" asp-area="" asp-controller="AjaxFormUpload" asp-action="Index">AJAX Form Upload</a>
    <a class="btn btn-secondary" asp-area="" asp-controller="FormUpload" asp-action="Index">Form Upload (Submit)</a>
</div>

UploadThing.Example.AspNetCoreMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UploadThing.Example.AspNetCoreMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UploadThing.Example.AspNetCoreMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UploadThing.Example.AspNetCoreMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AjaxFormUpload" asp-action="Index">AJAX Form</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FormUpload" asp-action="Index">Form</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div id="alert-parent"></div>

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UploadThing.Example.AspNetCoreMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        const connection = new signalR.HubConnectionBuilder().withUrl("/alerthub").build();

        connection.on("ReceiveAlert", (message) => {
            const alertDiv = document.createElement("div");
            alertDiv.className = "alert alert-success alert-dismissible fade show";
            alertDiv.setAttribute("role", "alert");
            alertDiv.id = "alertMessage";
            alertDiv.innerHTML = `
                <p>${message}<\p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            `;
            document.getElementById("alert-parent").appendChild(alertDiv);
        });

        connection.start().then(() => {
            console.log("SignalR Initiated");
        }).catch((err) => {
            return console.error(err.toString());
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>